name: 환율 알림 봇

on:
  schedule:
    # 매 시간 5분에 실행 (1:05, 2:05, 3:05 ...)
    - cron: '5 * * * *'
  workflow_dispatch:      # 수동 실행 버튼

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4 # v3 -> v4 업데이트

      - name: 파이썬 설치
        uses: actions/setup-python@v5 # v4 -> v5 업데이트
        with:
          python-version: '3.10'

      - name: 필요한 도구 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 봇 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
